# Generated by Django 5.0.1 on 2024-01-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_doorblock_article_doorblock_opening_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('depth', models.IntegerField()),
                ('width_back_indent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='doorblock',
            name='frame',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.frame'),
            preserve_default=False,
        ),
    ]
