# Generated by Django 5.0.1 on 2024-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_frame_doorblock_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorblock',
            name='al_banding_canvas',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doorblock',
            name='profile_frame_color',
            field=models.CharField(default='Аннодированый', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doorblock',
            name='seal_color',
            field=models.CharField(default='Серый', max_length=50),
            preserve_default=False,
        ),
    ]
