# Generated by Django 5.0.1 on 2024-01-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_doorblock_al_banding_canvas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorblock',
            name='is_primed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
