# Generated by Django 5.0.1 on 2024-01-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_excelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
