# Generated by Django 5.0.1 on 2024-02-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_doorblock_is_primed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf', models.CharField(max_length=100)),
                ('html', models.TextField()),
            ],
        ),
    ]
