# Generated by Django 5.0.1 on 2024-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
