# Generated by Django 5.0.1 on 2024-02-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_table_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order_id',
        ),
    ]
