# Generated by Django 5.0.1 on 2024-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_table_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='csrf',
        ),
        migrations.AddField(
            model_name='table',
            name='delivery',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='install',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='measurements',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='prepayment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='remainder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='total_ex_vat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='total_with_sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
