# Generated by Django 5.0.1 on 2024-02-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_table_csrf_table_delivery_table_install_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='delivery',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='install',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='measurements',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='prepayment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='remainder',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='sale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='total_ex_vat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='total_with_sale',
            field=models.FloatField(),
        ),
    ]
