# Generated by Django 5.0.1 on 2024-02-14 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_table_delivery_alter_table_install_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='client',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='client_contact',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 13, 53, 6, 684963)),
        ),
        migrations.AddField(
            model_name='table',
            name='delivery_info',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='manager',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='manager_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
