# Generated by Django 5.0.1 on 2024-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_table_city_table_client_table_client_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default='14.02.2024'),
        ),
    ]
