# Generated by Django 5.0.1 on 2024-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_doorblock_opening_type2_alter_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doorblock',
            name='article',
        ),
        migrations.RemoveField(
            model_name='doorblock',
            name='opening_type',
        ),
        migrations.RemoveField(
            model_name='doorblock',
            name='opening_type2',
        ),
    ]
