# Generated by Django 5.0.3 on 2024-03-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0021_frame_opening_type_frame_opening_type2"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="note",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="table",
            name="date",
            field=models.DateField(default="2024-03-13"),
        ),
    ]
