# Generated by Django 5.0.3 on 2024-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0022_table_note_alter_table_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="order_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
