# Generated by Django 5.0.3 on 2024-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0023_table_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="poslugy",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
