# Generated by Django 5.0.3 on 2024-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_table_date_alter_table_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorblock',
            name='diller_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default='2024-04-23'),
        ),
    ]
