# Generated by Django 5.0.3 on 2024-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_doorblock_diller_price_alter_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='price_type',
            field=models.TextField(default='RRC'),
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default='2024-04-24'),
        ),
    ]
