# Generated by Django 5.0.3 on 2024-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_table_price_type_alter_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_set_price_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default='2024-04-29'),
        ),
    ]
